{
 "title": "Drift Monitoring Dashboard - by Model",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ModelFilter", "label": "Model ID Filter" }
  ]
 },
 "panels": [
  { "title": "Dashboard Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Model Drift Monitoring\n\n  This dashboard performs checks for concept drift, prediction drift, and prior drift.  Data drift (drift in the features) is not available at this time.\n\n  The filter at the top focuses the entire dashboard to 1  model.\n"
   }
  },
  { "title": "Concept Drift", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Concept Drift",
   "type": "timeseries",
   "description": "<strong>Classifiers</strong><br/>\nDrift is detected when the p-value of the Chi-squared test falls below 0.05 (the 95% confidence interval).\n<br/><br/>\n<strong>Regression</strong><br/>\nDrift is detected when the p-value of the Kolmogorov-Smirnov (KS) test falls below 0.05 (the 95% confidence interval).\n<br/><br/>\nConcept Drift = when the distribution of model errors has changed, relative to the distribution of errors for the training set.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "drift_monitoring_api_model_concept_drift",
     "legendFormat": "Model ID {{model_id}}"
    }
   ]
  },
  {
   "title": "Error Distribution Earth Mover's Distance",
   "type": "timeseries",
   "description": "<a href=\"https://en.wikipedia.org/wiki/Earth_mover%27s_distance\">Earth Mover's Distance (EMD)</a> measures the similarity between the distribution of the training set's errors and the distribution of the current errors.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "drift_monitoring_api_model_concept_emd",
     "legendFormat": "Model ID {{model_id}}"
    }
   ]
  },
  { "title": "Prediction Drift", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "description": "<strong>Classifiers</strong><br/>\nPrediction drift is detected when the Chi-squared p-value falls below 0.05 (the 95% confidence interval).\n<strong>Regression</strong><br/>\nPrediction drift is detected when the Kolmogorov-Smirnov p-value falls below 0.05 (the 95% confidence interval).\n<br/><br/>\nPrediction Drift = when the distribution of the model predictions has changed, relative to the prediction distribution of the training set.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "drift_monitoring_api_model_prediction_drift",
     "legendFormat": "Model ID {{model_id}}"
    }
   ]
  },
  {
   "title": "Prediction Probability Drift (Classifiers Only)",
   "type": "timeseries",
   "description": "<strong>Classifiers</strong><br/>\nPrediction probability drift is detected when the Kolmogorov-Smirnov p-value falls below 0.05 (the 95% confidence interval).\n<br/><br/>\nPrediction Probability Drift = when the distribution of the model prediction probabilities has changed, relative to the prediction probability distribution of the training set.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "drift_monitoring_api_model_prediction_prob_drift",
     "legendFormat": "Model ID {{model_id}}"
    }
   ]
  },
  {
   "title": "Prediction Earth Mover's Distance",
   "type": "timeseries",
   "description": "<a href=\"https://en.wikipedia.org/wiki/Earth_mover%27s_distance\">Earth Mover's Distance (EMD)</a> measures the similarity between the distribution of the training set's predictions and the distribution of the current predictions.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "drift_monitoring_api_model_prediction_emd",
     "legendFormat": "Model ID {{model_id}}"
    }
   ]
  },
  { "title": "Prior Drift", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Prior Drift",
   "type": "timeseries",
   "description": "<strong>Classifiers</strong><br/>\nPrior drift is detected when the Chi-squared p-value falls below 0.05 (the 95% confidence interval).\n<strong>Regression</strong><br/>\nPrior drift is detected when the Kolmogorov-Smirnov p-value falls below 0.05 (the 95% confidence interval).\n<br/><br/>\nPrior Drift = when the distribution of the ground truth labels has changed, relative to the prediction distribution of the training set.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "drift_monitoring_api_model_prior_drift",
     "legendFormat": "Model ID {{model_id}}"
    }
   ]
  },
  {
   "title": "Ground Truth Earth Mover's Distance",
   "type": "timeseries",
   "description": "<a href=\"https://en.wikipedia.org/wiki/Earth_mover%27s_distance\">Earth Mover's Distance (EMD)</a> measures the similarity between the distribution of the training set's ground truth labels and the distribution of the current ground truth labels.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "drift_monitoring_api_model_prior_emd",
     "legendFormat": "Model ID {{model_id}}"
    }
   ]
  }
 ]
}