{
 "title": "Drift Monitoring Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Model Drift Monitoring\n\n  This dashboard performs checks for concept drift and data drift.\n"
   }
  },
  { "title": "Concept and Prior Drift", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Prior and Concept Drift Chi-Squared p-values",
   "type": "timeseries",
   "description": "Drift is detected when the p-value of the Chi-squared test falls below 0.05 (the 95% confidence interval).\n<br/><br/>\nPrior Drift = Target Drift = when the distribution of the ground truth labels has shifted between the training set and current data\n<br/><br/>\nConcept Drift = Prediction drift = when the distribution of the predicted class has shifted between the training set and current data, representing a change in the relationship between the target and the features.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "evidently:concept_drift:prediction_drift",
     "legendFormat": "Concept Drift"
    },
    {
     "expr": "evidently:concept_drift:target_drift",
     "legendFormat": "Prior Drift"
    }
   ]
  },
  { "title": "Data Drift", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "% of Features with Drift",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "evidently:data_drift:share_drifted_features",
     "legendFormat": "% Features"
    }
   ]
  },
  {
   "title": "# of Drifted Features",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_drift:n_drifted_features",
     "legendFormat": "Drifted"
    }
   ]
  },
  {
   "title": "Total # of Features",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "evidently:data_drift:n_drifted_features / evidently:data_drift:share_drifted_features",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Chi-Squared p-value by Feature",
   "type": "timeseries",
   "description": "Data drift is detected when the Chi-squared p-value falls below 0.05 (the 95% confidence interval).\n<br/><br/>\nFeature frequencies are treated as categorical bins.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "evidently:data_drift:p_value", "legendFormat": "{{feature}}" }
   ]
  }
 ]
}